#!/bin/bash

if [ -d /home/dicer/.eclipse ]; then
  sudo chown dicer:dicer /home/dicer/.eclipse
fi
exec /opt/eclipse/eclipse -nosplash -import /opt/D4D -data /workspace
 
#exec /opt/eclipse/eclipse -noSplash -data /opt/STUFF/eclipse_work -configuration /opt/STUFF/eclipse_home -user /opt/STUFF/eclipse_home 
